<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\AirlineCompany.Core\AirlineCompany.Core.csproj" />
  	<ProjectReference Include="..\AirlineCompany.DTO\AirlineCompany.DTO.csproj" />
  </ItemGroup>
	
</Project>
