// <auto-generated />
using System;
using AirlineCompany.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineCompany.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211101240_InitialCreateWithSeedData")]
    partial class InitialCreateWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirlineCompany.Core.Entities.AircraftFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AircraftFamilies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Airbus",
                            Name = "A320"
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Boeing",
                            Name = "737"
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Airbus",
                            Name = "A330"
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "Boeing",
                            Name = "777"
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "Airbus",
                            Name = "A350"
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "Boeing",
                            Name = "787"
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "Bombardier",
                            Name = "CRJ"
                        },
                        new
                        {
                            Id = 8,
                            Manufacturer = "Embraer",
                            Name = "E-Jet"
                        },
                        new
                        {
                            Id = 9,
                            Manufacturer = "Airbus",
                            Name = "A220"
                        },
                        new
                        {
                            Id = 10,
                            Manufacturer = "Boeing",
                            Name = "747"
                        });
                });

            modelBuilder.Entity("AirlineCompany.Core.Entities.AircraftModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftFamilyId")
                        .HasColumnType("int");

                    b.Property<double>("CargoCapacity")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AircraftFamilyId");

                    b.ToTable("AircraftModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AircraftFamilyId = 1,
                            CargoCapacity = 4.5,
                            Name = "A320-200",
                            PassengerCapacity = 180,
                            Range = 6100
                        },
                        new
                        {
                            Id = 2,
                            AircraftFamilyId = 1,
                            CargoCapacity = 5.2000000000000002,
                            Name = "A321neo",
                            PassengerCapacity = 240,
                            Range = 7400
                        },
                        new
                        {
                            Id = 3,
                            AircraftFamilyId = 2,
                            CargoCapacity = 4.7999999999999998,
                            Name = "737-800",
                            PassengerCapacity = 189,
                            Range = 5765
                        },
                        new
                        {
                            Id = 4,
                            AircraftFamilyId = 2,
                            CargoCapacity = 5.0999999999999996,
                            Name = "737 MAX 8",
                            PassengerCapacity = 210,
                            Range = 6570
                        },
                        new
                        {
                            Id = 5,
                            AircraftFamilyId = 3,
                            CargoCapacity = 12.5,
                            Name = "A330-300",
                            PassengerCapacity = 440,
                            Range = 10800
                        },
                        new
                        {
                            Id = 6,
                            AircraftFamilyId = 4,
                            CargoCapacity = 16.5,
                            Name = "777-300ER",
                            PassengerCapacity = 550,
                            Range = 13650
                        },
                        new
                        {
                            Id = 7,
                            AircraftFamilyId = 5,
                            CargoCapacity = 14.5,
                            Name = "A350-900",
                            PassengerCapacity = 440,
                            Range = 15000
                        },
                        new
                        {
                            Id = 8,
                            AircraftFamilyId = 6,
                            CargoCapacity = 13.5,
                            Name = "787-9",
                            PassengerCapacity = 420,
                            Range = 14140
                        },
                        new
                        {
                            Id = 9,
                            AircraftFamilyId = 7,
                            CargoCapacity = 2.5,
                            Name = "CRJ-900",
                            PassengerCapacity = 90,
                            Range = 2870
                        },
                        new
                        {
                            Id = 10,
                            AircraftFamilyId = 8,
                            CargoCapacity = 3.7999999999999998,
                            Name = "E195-E2",
                            PassengerCapacity = 146,
                            Range = 4815
                        });
                });

            modelBuilder.Entity("AirlineCompany.Core.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftModelId")
                        .HasColumnType("int");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AircraftModelId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AircraftModelId = 1,
                            ArrivalCity = "London",
                            ArrivalDate = new DateTime(2025, 12, 6, 18, 12, 40, 95, DateTimeKind.Local).AddTicks(779),
                            Code = "SU100",
                            DepartureCity = "Moscow",
                            DepartureDate = new DateTime(2025, 12, 6, 14, 12, 40, 95, DateTimeKind.Local).AddTicks(768),
                            Duration = new TimeSpan(0, 4, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            AircraftModelId = 2,
                            ArrivalCity = "Paris",
                            ArrivalDate = new DateTime(2025, 12, 8, 17, 42, 40, 95, DateTimeKind.Local).AddTicks(785),
                            Code = "SU200",
                            DepartureCity = "Moscow",
                            DepartureDate = new DateTime(2025, 12, 8, 14, 12, 40, 95, DateTimeKind.Local).AddTicks(785),
                            Duration = new TimeSpan(0, 3, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            AircraftModelId = 3,
                            ArrivalCity = "New York",
                            ArrivalDate = new DateTime(2025, 12, 9, 22, 12, 40, 95, DateTimeKind.Local).AddTicks(788),
                            Code = "SU300",
                            DepartureCity = "London",
                            DepartureDate = new DateTime(2025, 12, 9, 14, 12, 40, 95, DateTimeKind.Local).AddTicks(787),
                            Duration = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            AircraftModelId = 4,
                            ArrivalCity = "Tokyo",
                            ArrivalDate = new DateTime(2025, 12, 11, 2, 12, 40, 95, DateTimeKind.Local).AddTicks(790),
                            Code = "SU400",
                            DepartureCity = "Paris",
                            DepartureDate = new DateTime(2025, 12, 10, 14, 12, 40, 95, DateTimeKind.Local).AddTicks(789),
                            Duration = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            AircraftModelId = 5,
                            ArrivalCity = "Dubai",
                            ArrivalDate = new DateTime(2025, 12, 11, 20, 12, 40, 95, DateTimeKind.Local).AddTicks(792),
                            Code = "SU500",
                            DepartureCity = "Berlin",
                            DepartureDate = new DateTime(2025, 12, 11, 14, 12, 40, 95, DateTimeKind.Local).AddTicks(792),
                            Duration = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            AircraftModelId = 6,
                            ArrivalCity = "Singapore",
                            ArrivalDate = new DateTime(2025, 12, 12, 21, 12, 40, 95, DateTimeKind.Local).AddTicks(794),
                            Code = "SU600",
                            DepartureCity = "Dubai",
                            DepartureDate = new DateTime(2025, 12, 12, 14, 12, 40, 95, DateTimeKind.Local).AddTicks(794),
                            Duration = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            AircraftModelId = 7,
                            ArrivalCity = "Sydney",
                            ArrivalDate = new DateTime(2025, 12, 13, 22, 12, 40, 95, DateTimeKind.Local).AddTicks(796),
                            Code = "SU700",
                            DepartureCity = "Singapore",
                            DepartureDate = new DateTime(2025, 12, 13, 14, 12, 40, 95, DateTimeKind.Local).AddTicks(796),
                            Duration = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            AircraftModelId = 8,
                            ArrivalCity = "Los Angeles",
                            ArrivalDate = new DateTime(2025, 12, 15, 4, 12, 40, 95, DateTimeKind.Local).AddTicks(799),
                            Code = "SU800",
                            DepartureCity = "Sydney",
                            DepartureDate = new DateTime(2025, 12, 14, 14, 12, 40, 95, DateTimeKind.Local).AddTicks(798),
                            Duration = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            AircraftModelId = 9,
                            ArrivalCity = "Tokyo",
                            ArrivalDate = new DateTime(2025, 12, 16, 1, 12, 40, 95, DateTimeKind.Local).AddTicks(801),
                            Code = "SU900",
                            DepartureCity = "Los Angeles",
                            DepartureDate = new DateTime(2025, 12, 15, 14, 12, 40, 95, DateTimeKind.Local).AddTicks(800),
                            Duration = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            AircraftModelId = 10,
                            ArrivalCity = "Moscow",
                            ArrivalDate = new DateTime(2025, 12, 17, 0, 12, 40, 95, DateTimeKind.Local).AddTicks(803),
                            Code = "SU1000",
                            DepartureCity = "Tokyo",
                            DepartureDate = new DateTime(2025, 12, 16, 14, 12, 40, 95, DateTimeKind.Local).AddTicks(802),
                            Duration = new TimeSpan(0, 10, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("AirlineCompany.Core.Entities.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PassportNumber")
                        .IsUnique();

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ivanov Ivan Ivanovich",
                            PassportNumber = "3600-123456"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Petrov Petr Petrovich",
                            PassportNumber = "3605-654321"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1985, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Sidorova Anna Sergeevna",
                            PassportNumber = "3610-987654"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1978, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Kuznetsov Alexey Vladimirovich",
                            PassportNumber = "3615-456789"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1992, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Smirnova Elena Dmitrievna",
                            PassportNumber = "3620-135790"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1988, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Popov Mikhail Igorevich",
                            PassportNumber = "3624-246801"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1983, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Volkova Olga Nikolaevna",
                            PassportNumber = "3602-112233"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1995, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Novikov Dmitry Andreevich",
                            PassportNumber = "3608-445566"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1987, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Fedorova Maria Pavlovna",
                            PassportNumber = "3612-778899"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1975, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Orlov Sergey Viktorovich",
                            PassportNumber = "3618-990011"
                        });
                });

            modelBuilder.Entity("AirlineCompany.Core.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BaggageWeight")
                        .HasColumnType("float");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("HasHandLuggage")
                        .HasColumnType("bit");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("FlightId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaggageWeight = 15.5,
                            FlightId = 1,
                            HasHandLuggage = true,
                            PassengerId = 1,
                            SeatNumber = "10A"
                        },
                        new
                        {
                            Id = 2,
                            BaggageWeight = 0.0,
                            FlightId = 1,
                            HasHandLuggage = false,
                            PassengerId = 2,
                            SeatNumber = "10B"
                        },
                        new
                        {
                            Id = 3,
                            BaggageWeight = 10.0,
                            FlightId = 1,
                            HasHandLuggage = true,
                            PassengerId = 3,
                            SeatNumber = "10C"
                        },
                        new
                        {
                            Id = 4,
                            BaggageWeight = 12.0,
                            FlightId = 2,
                            HasHandLuggage = true,
                            PassengerId = 4,
                            SeatNumber = "15A"
                        },
                        new
                        {
                            Id = 5,
                            BaggageWeight = 8.5,
                            FlightId = 2,
                            HasHandLuggage = true,
                            PassengerId = 5,
                            SeatNumber = "15B"
                        },
                        new
                        {
                            Id = 6,
                            BaggageWeight = 0.0,
                            FlightId = 2,
                            HasHandLuggage = false,
                            PassengerId = 6,
                            SeatNumber = "15C"
                        },
                        new
                        {
                            Id = 7,
                            BaggageWeight = 20.0,
                            FlightId = 3,
                            HasHandLuggage = true,
                            PassengerId = 7,
                            SeatNumber = "20A"
                        },
                        new
                        {
                            Id = 8,
                            BaggageWeight = 5.5,
                            FlightId = 3,
                            HasHandLuggage = true,
                            PassengerId = 8,
                            SeatNumber = "20B"
                        },
                        new
                        {
                            Id = 9,
                            BaggageWeight = 0.0,
                            FlightId = 4,
                            HasHandLuggage = false,
                            PassengerId = 9,
                            SeatNumber = "25A"
                        },
                        new
                        {
                            Id = 10,
                            BaggageWeight = 18.0,
                            FlightId = 4,
                            HasHandLuggage = true,
                            PassengerId = 10,
                            SeatNumber = "25B"
                        },
                        new
                        {
                            Id = 11,
                            BaggageWeight = 7.5,
                            FlightId = 4,
                            HasHandLuggage = true,
                            PassengerId = 1,
                            SeatNumber = "25C"
                        },
                        new
                        {
                            Id = 12,
                            BaggageWeight = 0.0,
                            FlightId = 4,
                            HasHandLuggage = false,
                            PassengerId = 2,
                            SeatNumber = "25D"
                        },
                        new
                        {
                            Id = 13,
                            BaggageWeight = 9.0,
                            FlightId = 5,
                            HasHandLuggage = true,
                            PassengerId = 3,
                            SeatNumber = "30A"
                        },
                        new
                        {
                            Id = 14,
                            BaggageWeight = 11.0,
                            FlightId = 6,
                            HasHandLuggage = true,
                            PassengerId = 4,
                            SeatNumber = "35A"
                        },
                        new
                        {
                            Id = 15,
                            BaggageWeight = 0.0,
                            FlightId = 6,
                            HasHandLuggage = false,
                            PassengerId = 5,
                            SeatNumber = "35B"
                        },
                        new
                        {
                            Id = 16,
                            BaggageWeight = 6.5,
                            FlightId = 6,
                            HasHandLuggage = true,
                            PassengerId = 6,
                            SeatNumber = "35C"
                        },
                        new
                        {
                            Id = 17,
                            BaggageWeight = 14.0,
                            FlightId = 7,
                            HasHandLuggage = true,
                            PassengerId = 7,
                            SeatNumber = "40A"
                        },
                        new
                        {
                            Id = 18,
                            BaggageWeight = 0.0,
                            FlightId = 7,
                            HasHandLuggage = false,
                            PassengerId = 8,
                            SeatNumber = "40B"
                        },
                        new
                        {
                            Id = 19,
                            BaggageWeight = 16.5,
                            FlightId = 8,
                            HasHandLuggage = true,
                            PassengerId = 9,
                            SeatNumber = "45A"
                        },
                        new
                        {
                            Id = 20,
                            BaggageWeight = 13.0,
                            FlightId = 9,
                            HasHandLuggage = true,
                            PassengerId = 10,
                            SeatNumber = "50A"
                        },
                        new
                        {
                            Id = 21,
                            BaggageWeight = 0.0,
                            FlightId = 9,
                            HasHandLuggage = false,
                            PassengerId = 1,
                            SeatNumber = "50B"
                        },
                        new
                        {
                            Id = 22,
                            BaggageWeight = 8.0,
                            FlightId = 10,
                            HasHandLuggage = true,
                            PassengerId = 2,
                            SeatNumber = "55A"
                        },
                        new
                        {
                            Id = 23,
                            BaggageWeight = 19.5,
                            FlightId = 10,
                            HasHandLuggage = true,
                            PassengerId = 3,
                            SeatNumber = "55B"
                        },
                        new
                        {
                            Id = 24,
                            BaggageWeight = 0.0,
                            FlightId = 10,
                            HasHandLuggage = false,
                            PassengerId = 4,
                            SeatNumber = "55C"
                        });
                });

            modelBuilder.Entity("AirlineCompany.Core.Entities.AircraftModel", b =>
                {
                    b.HasOne("AirlineCompany.Core.Entities.AircraftFamily", "AircraftFamily")
                        .WithMany("Models")
                        .HasForeignKey("AircraftFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AircraftFamily");
                });

            modelBuilder.Entity("AirlineCompany.Core.Entities.Flight", b =>
                {
                    b.HasOne("AirlineCompany.Core.Entities.AircraftModel", "AircraftModel")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AircraftModel");
                });

            modelBuilder.Entity("AirlineCompany.Core.Entities.Ticket", b =>
                {
                    b.HasOne("AirlineCompany.Core.Entities.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirlineCompany.Core.Entities.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("AirlineCompany.Core.Entities.AircraftFamily", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("AirlineCompany.Core.Entities.AircraftModel", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AirlineCompany.Core.Entities.Flight", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AirlineCompany.Core.Entities.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
